#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
TFC - Onion-routed, endpoint secure messaging system
Copyright (C) 2013-2026  Markus Ottela

This file is part of TFC.
TFC is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. TFC is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with TFC. If not, see
<https://www.gnu.org/licenses/>.
"""

import os

from src.common.exceptions import CriticalError
from src.common.crypto.algorithms.blake2b import blake2b
from src.common.statics import KeyLength


def csprng(key_length: KeyLength) -> bytes:
    """Generate a cryptographically secure random key.

    The key is generated by the Linux kernel's modern, ChaCha20-based
    cryptographically secure pseudo-random number generator (CSPRNG),
    also known as the Linux-RNG, or LRNG.

    The LRNG is currently receiving a lot of love from Jason Donenfeld,
    and no documentation, not even the one maintained by the German
    BSI, is keeping up with the overhaul.

    The best resource to study the RNG functionality is for now, the source code itself:
        https://github.com/torvalds/linux/blob/master/drivers/char/random.c
    """
    if not isinstance(key_length, KeyLength):
        raise CriticalError('Key length needs to be defined in KeyLength enum.')

    entropy = os.getrandom(key_length)  # type: bytes

    if not isinstance(entropy, bytes):
        raise CriticalError(f'GETRANDOM returned invalid type data ({type(entropy)}).')

    if len(entropy) != key_length:
        raise CriticalError(f'GETRANDOM returned invalid amount of entropy ({len(entropy)} bytes).')

    compressed = blake2b(entropy, digest_size=key_length)

    return compressed
