#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
TFC - Onion-routed, endpoint secure messaging system
Copyright (C) 2013-2026  Markus Ottela

This file is part of TFC.
TFC is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. TFC is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with TFC. If not, see
<https://www.gnu.org/licenses/>.
"""

from cryptography.hazmat.primitives.asymmetric.x448 import X448PrivateKey, X448PublicKey

from src.common.exceptions import CriticalError
from src.common.crypto.algorithms.blake2b import blake2b
from src.common.crypto.fingerprint import FingerprintUser, FingerprintContact
from src.common.crypto.keys.symmetric_key import (X448SharedKey, HeaderKeyUser, MessageKeyUser, HeaderKeyContact,
                                                  MessageKeyContact)
from src.common.statics import CryptoVarLength, KeyLength, DomainSeparator


class X448:

    """\
    X448 is the Diffie-Hellman function for Curve448-Goldilocks, a
    state-of-the-art elliptical curve published by Mike Hamburg in 2014.

    For more details, see
        https://eprint.iacr.org/2015/625.pdf
        https://ed448goldilocks.sourceforge.net/
        https://en.wikipedia.org/wiki/Curve448

    The reasons for using X448 in TFC include

        o Curve448 meets the criterion for a SafeCurve[1]:

          Parameters

            - Use of large prime field (p = 2^448 - 2^224 - 1).

            - The Edwards curve (x^2+y^2 = 1-39081x^2y^2) is complete.

            - The base point (x_1,y_1) is on the curve.

          ECDLP security

            - 222.8-bit security against the Pollard's rho method.
                  This is important as the security of hash ratchet
              depends on the security of the root key. Curve25519 is
              thus less feasible choice. Curve448 is also likely to
              resist quantum computers and mathematical breakthroughs
              against ECC for a longer time.

            - Safe against additive and multiplicative transfer.

            - The complex-multiplication field discriminant is 2^447.5,
              which is much larger than the required minimum (2^100).

            - The curve-generation process is fully rigid, i.e. it has
              been completely explained. In comparison, NIST P-curves
              use coefficients generated by hashing unexplained seeds.

          ECC security

            - Use of Montgomery ladder that protects from side channel
              attacks by doing constant-time single-scalar multiplication.

            - 221.8-bit security against twist attacks (small-subgroup
              attack combined with invalid-curve attack).

            - Support for complete single-scalar and multi-scalar
              multiplication formulas.

            - Points on Curve448 (e.g. public keys) are
              indistinguishable from uniform random strings.

        o Safer curves (M-511 and E-521) do not have robust implementations.

        o NIST has announced X448 will be included in the SP 800-186.[2]

        o Its public keys do not require validation as long as the
          resulting shared secret is not zero:

          '[X448] is actually two curves, where any patterns of bits
           will be interpreted as a point on one of the curves or on the
           other.'[3]

        o Its public keys are reasonably short (84 chars when WIF-encoded)
          to be manually typed from Networked Computer to Source Computer.

    The correctness of the X448 implementation[4] is tested by TFC unit
    tests. The testing is done in limited scope by using the official
    test vectors.

     [1] https://safecurves.cr.yp.to/
     [2] https://csrc.nist.gov/News/2017/Transition-Plans-for-Key-Establishment-Schemes
     [3] https://crypto.stackexchange.com/a/44348
     [4] https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable/crypto/ec/curve448
         https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/asymmetric/x448.py
    """

    @staticmethod
    def generate_private_key() -> 'X448PrivateKey':
        """Generate the X448 private key.

        The pyca/cryptography's key generation process is as follows:

        1. When `X448PrivateKey.generate()` is called by this method,
           the `generate()` class method imports the OpenSSL backend[1].

        2. Importing the backend causes Python to call the Backend
           class[2] that runs the `__init__()` method of the class[3],
           which then calls the `activate_osrandom_engine()` instance
           method[4].

         [1] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/primitives/asymmetric/x448.py#L39
         [2] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L2708
         [3] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L222
         [4] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L238

        ---

        If the OpenSSL version is older than 1.1.1d:

        3. Calling the `activate_osrandom_engine()` disables the default
           OpenSSL CSPRNG, and activates the pyca/cryptography
           'OS random engine'.[5]

        4. Unlike the old OpenSSL user-space CSPRNG that only seeds from
           /dev/urandom, the OS random engine uses the GETRANDOM(0)
           syscall that sources all of its entropy directly from the
           LRNG's ChaCha20 DRNG. The OS random engine does not suffer
           from the fork-weakness where forked process is not
           automatically reseeded, and it's also safe from issues with
           OpenSSL's CSPRNG initialization.[6]

        5. The fallback option (/dev/urandom) of OS random engine might
           be problematic on pre-3.17 kernels if the CSPRNG has not been
           properly seeded. However, TFC checks that the kernel version
           of the OS it's running on is at least 4.17. This means that
           the used source of entropy is always GETRANDOM(0).[7] This
           can be verified from the source code as well: The last
           parameter `0` of the GETRANDOM syscall[8] indicates
           GRND_NONBLOCK flag is not set. This means the ChaCha20 DRNG
           is used, and that it does not yield entropy until it has been
           fully seeded. This is the same case as with TFC's `csprng()`
           function.

         [5] https://cryptography.io/en/latest/hazmat/backends/openssl/#activate_osrandom_engine
         [6] https://cryptography.io/en/latest/hazmat/backends/openssl/#os-random-engine
         [7] https://cryptography.io/en/latest/hazmat/backends/openssl/#os-random-sources
         [8] https://github.com/pyca/cryptography/blob/3.1.1/src/_cffi_src/openssl/src/osrandom_engine.c#L396

        ---

        If the OpenSSL version used is 1.1.1d or newer:

        3. The Backend init method calls[9] the
           `activate_osrandom_engine` method, which will check[10]
           whether OS Random Engine is needed, and since with
           OpenSSL 1.1.1d+ it is not, the condition check will evaluate
           as `False`, which in turn means the entire method is skipped.

        4. The `generate` method will then call the
           `backend.x448_generate_key()`[11] which in turn will call
           the `_evp_pkey_keygen_gc` method[12].

        7. The `_evp_pkey_keygen_gc` calls the `EVP_PKEY_keygen`
           method[13], that given the context will generate the X448
           private key.

        8. To quote OpenSSL's change log[14]:

            'On older Linux systems where the getrandom() system call is
             not available, OpenSSL normally uses the /dev/urandom device
             for seeding its CSPRNG. Contrary to getrandom(), the
             /dev/urandom device will not block during early boot when
             the kernel CSPRNG has not been seeded yet.'

           Again, as TFC checks that the kernel version of the OS it's
           running on is at least 4.17, the entropy source used by
           OpenSSL is always GETRANDOM(0).

         [9] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L238
        [10] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L288
        [11] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/primitives/asymmetric/x448.py#L46
        [12] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L2365
        [13] https://github.com/pyca/cryptography/blob/3.1.1/src/cryptography/hazmat/backends/openssl/backend.py#L2326
        [14] https://www.openssl.org/news/changelog.html#openssl-111
        """
        return X448PrivateKey.generate()

    @staticmethod
    def derive_public_key(private_key: 'X448PrivateKey') -> X448PublicKey:
        """Derive public key from an X448 private key."""
        return private_key.public_key()

    @staticmethod
    def shared_key(private_key: 'X448PrivateKey', public_key: 'X448PublicKey') -> 'X448SharedKey':
        """Derive the X448 shared key.

        The pyca/cryptography library validates the length of the public
        key and verifies that the shared secret is not zero.

        The X448 shared secret is not a random byte string, but a random
        point on the curve. Thus, the raw bits of the shared secret
        might not be uniformly distributed in the keyspace, but have
        bias towards 0 or 1.
            To get rid of the bias, the raw shared secret is passed
        through a computational extractor (BLAKE2b CSPRF) to ensure
        a uniformly random shared key.

        While `shared secret` and `shared key` are used synonymously, in
        TFC we choose to distinguish between the raw shared secret and
        the BLAKE2b compressed shared secret by calling only the latter
        the `shared key`.

        Note that the shared key won't be used directly as a session
        key. Instead, it will be used as the key parameter in separate
        BLAKE2b instances where the hash function is used as a KDF to
        extract unidirectional message/header keys and fingerprints.
        """
        try:
            shared_secret = private_key.exchange(public_key)  # type: bytes
        except ValueError as e:
            raise CriticalError(str(e))

        if not isinstance(shared_secret, bytes):  # pragma: no cover
            raise CriticalError(f'Derived an invalid type ({type(shared_secret)}) shared secret.')

        if len(shared_secret) != CryptoVarLength.X448_SHARED_SECRET:  # pragma: no cover
            raise CriticalError(f'Generated an invalid size shared secret ({len(shared_secret)} bytes).')

        shared_key_bytes = blake2b(shared_secret, digest_size=KeyLength.SYMMETRIC_KEY.value)

        return X448SharedKey(shared_key_bytes)

    @staticmethod
    def derive_subkeys(shared_key             : 'X448SharedKey',
                       tfc_public_key_user    : X448PublicKey,
                       tfc_public_key_contact : X448PublicKey
                       ) -> tuple['HeaderKeyUser',    'MessageKeyUser',
                                  'HeaderKeyContact', 'MessageKeyContact',
                                  'FingerprintUser',  'FingerprintContact']:
        """\
        Create domain separated message and header subkeys and fingerprints
        from the shared key.

        Domain separate unidirectional keys from shared key by using public
        keys as message and the context variable as personalization string.

        Domain separate fingerprints of public keys by using the shared
        secret as key and the context variable as personalization string.
        This way entities who might monitor fingerprint verification
        channel are unable to correlate spoken values with public keys
        that they might see on RAM or screen of Networked Computer:
        Public keys can not be derived from the fingerprints due to
        preimage resistance of BLAKE2b, and fingerprints can not be
        derived from public key without the X448 shared key. Using the
        context variable ensures fingerprints are distinct from derived
        message and header keys.
        """
        contact_pub_key_bytes = tfc_public_key_contact.public_bytes_raw()
        user_pub_key_bytes    = tfc_public_key_user.public_bytes_raw()
        shared_bytes          = shared_key.raw_bytes

        tx_mk = blake2b(contact_pub_key_bytes, shared_bytes, person=DomainSeparator.MESSAGE_KEY.value, digest_size=KeyLength.SYMMETRIC_KEY.value)
        rx_mk = blake2b(user_pub_key_bytes,    shared_bytes, person=DomainSeparator.MESSAGE_KEY.value, digest_size=KeyLength.SYMMETRIC_KEY.value)

        tx_hk = blake2b(contact_pub_key_bytes, shared_bytes, person=DomainSeparator.HEADER_KEY.value, digest_size=KeyLength.SYMMETRIC_KEY.value)
        rx_hk = blake2b(user_pub_key_bytes,    shared_bytes, person=DomainSeparator.HEADER_KEY.value, digest_size=KeyLength.SYMMETRIC_KEY.value)

        tx_fp = blake2b(contact_pub_key_bytes, shared_bytes, person=DomainSeparator.FINGERPRINT.value, digest_size=CryptoVarLength.FINGERPRINT.value)
        rx_fp = blake2b(user_pub_key_bytes,    shared_bytes, person=DomainSeparator.FINGERPRINT.value, digest_size=CryptoVarLength.FINGERPRINT.value)

        key_tuple = tx_mk, rx_mk, tx_hk, rx_hk, tx_fp, rx_fp

        if len(set(key_tuple)) != len(key_tuple):
            raise CriticalError('Derived subkeys were not unique.')

        return (HeaderKeyUser(tx_hk),    MessageKeyUser(tx_mk),
                HeaderKeyContact(rx_hk), MessageKeyContact(rx_mk),
                FingerprintUser(tx_fp),  FingerprintContact(rx_fp))
