#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
TFC - Onion-routed, endpoint secure messaging system
Copyright (C) 2013-2026  Markus Ottela

This file is part of TFC.
TFC is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. TFC is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with TFC. If not, see
<https://www.gnu.org/licenses/>.
"""

import os

from typing import TYPE_CHECKING

from src.common.crypto.keys.onion_service_keys import OnionServicePrivateKey, OnionPublicKeyUser
from src.common.crypto.keys.symmetric_key import BufferKey
from src.common.types_custom import StrOnionAddressUser, BoolReplaceDB
from src.common.entities.confirm_code import ConfirmationCode
from src.common.utils.strings import separate_header
from src.common.utils.validators import validate_bytes
from src.database.database import TFCEncryptedDatabase
from src.common.statics import KeyLength, DBName

if TYPE_CHECKING:
    from src.database.db_masterkey import MasterKey
    from src.database.db_settings import Settings


class OnionService:
    """\
    OnionService object manages the persistent Ed25519 key used
    to create a v3 Tor Onion Service on the Networked Computer.

    The reason the key is generated by Transmitter Program on Source
    Computer, is this ensures that even when Networked Computer runs an
    amnesic Linux distribution like Tails, the long term private
    signing key is not lost between sessions.

    The private key for Onion Service can not be kept as protected as
    TFC's other private message/header keys (that never leave
    Source/Destination computer). This is however OK, as the Onion
    Service private key is only as secure as the networked endpoint
    anyway.
    """

    def __init__(self, master_key: 'MasterKey', settings: 'Settings') -> None:
        """Create a new OnionService object."""
        self.__master_key   = master_key
        self.__database     = TFCEncryptedDatabase(DBName.ONION_DB, self.__master_key, settings.program_id)
        self.__conf_code    = ConfirmationCode.generate()
        self.__is_delivered = False

        if os.path.isfile(self.__database.path_to_db):
            self.__onion_private_key, self.__buffer_key = self.__load_db()
        else:
            self.__onion_private_key = OnionServicePrivateKey()
            self.__buffer_key        = BufferKey()
            self.__store_db()

    @property
    def onion_private_key(self) -> OnionServicePrivateKey:
        """Export the Onion Service private key."""
        return self.__onion_private_key

    @property
    def buffer_key(self) -> BufferKey:
        """Export the Onion Service private key."""
        return self.__buffer_key

    @property
    def onion_pub_key_user(self) -> OnionPublicKeyUser:
        """Get the Onion Service public key."""
        return self.__onion_private_key.onion_pub_key

    @property
    def onion_addr_user(self) -> StrOnionAddressUser:
        """Get the full length Onion Address for the Onion Service."""
        return StrOnionAddressUser(self.__onion_private_key.onion_addr)

    @property
    def short_addr_user(self) -> str:
        """Get the short Onion Address for the Onion Service."""
        return self.__onion_private_key.short_addr

    @property
    def confirmation_code(self) -> ConfirmationCode:
        """Get the confirmation code."""
        return self.__conf_code

    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │                              Delivery Status                              │
    # └───────────────────────────────────────────────────────────────────────────┘

    @property
    def is_delivered(self) -> bool:
        """Check if the Onion Service is delivered."""
        return self.__is_delivered

    def mark_delivered(self) -> None:
        """Mark the Onion Service data as delivered."""
        self.__is_delivered = True
        self.__conf_code    = ConfirmationCode.generate()

    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │                                  Database                                 │
    # └───────────────────────────────────────────────────────────────────────────┘

    def __serialize(self) -> bytes:
        """Serialize the database into bytes."""
        return self.__onion_private_key.raw_private_bytes + self.__buffer_key.raw_bytes

    def __store_db(self, replace: BoolReplaceDB = BoolReplaceDB(True)) -> None:
        """Store Onion Service private key to an encrypted database."""
        self.__database.store_database(self.__serialize(), replace)

    def __load_db(self) -> tuple[OnionServicePrivateKey, BufferKey]:
        """Load the Onion Service private key from the encrypted database."""
        db_plaintext = self.__database.load_database()

        onion_service_private_bytes, buffer_key_bytes = separate_header(db_plaintext, header_length=KeyLength.ONION_SERVICE_PRIVATE_KEY)

        validate_bytes(onion_service_private_bytes, key='onion_service_private_bytes', is_length=KeyLength.ONION_SERVICE_PRIVATE_KEY, not_all_zeros=True)
        validate_bytes(buffer_key_bytes,            key='buffer_key_bytes',            is_length=KeyLength.SYMMETRIC_KEY,             not_all_zeros=True)

        onion_private_key = OnionServicePrivateKey(onion_service_private_bytes)
        buffer_key        = BufferKey(buffer_key_bytes)

        return onion_private_key, buffer_key

    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │                                  Rekeying                                 │
    # └───────────────────────────────────────────────────────────────────────────┘

    def rekey_to_temp_db(self, new_master_key: 'MasterKey') -> None:
        """Rekey the database to a temporary file."""
        self.__database.rekey_to_temp_db(new_master_key, self.__serialize())

    def migrate_to_rekeyed_db(self) -> None:
        """Migrate to the rekeyed database."""
        self.__database.migrate_to_rekeyed_db()
