#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
TFC - Onion-routed, endpoint secure messaging system
Copyright (C) 2013-2026  Markus Ottela

This file is part of TFC.
TFC is free software: you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. TFC is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with TFC. If not, see
<https://www.gnu.org/licenses/>.
"""

from typing import TYPE_CHECKING

from src.common.entities.serialized_command import SerializedCommand
from src.common.exceptions import SoftError, raise_if_traffic_masking
from src.common.entities.confirm_code import ConfirmationCode
from src.common.crypto.keys.symmetric_key import LocalKeyEncryptionKey
from src.common.statics import RxCommand, NCBypassState
from src.ui.common.input.get_nc_bypass_confirmation import get_nc_bypass_confirmation
from src.ui.common.input.get_confirmation_code import get_confirmation_code
from src.ui.common.output.print_message import print_message
from src.ui.common.output.vt100_utils import clear_previous_lines, reset_terminal
from src.ui.common.output.phase import phase
from src.ui.common.output.print_key import print_key
from src.datagrams.receiver.local_key import DatagramReceiverLocalKey
from src.transmitter.queue_packet.queue_packet import queue_command

if TYPE_CHECKING:
    from src.common.queues import TxQueue
    from src.database.db_local_key import LocalKeyDB
    from src.database.db_settings import Settings


def new_local_key(settings     : 'Settings',
                  queues       : 'TxQueue',
                  local_key_db : 'LocalKeyDB',
                  ) -> None:
    """Run local key exchange protocol.

    Local key encrypts commands and data sent from Source Computer to
    user's Destination Computer. The key is delivered to Destination
    Computer in packet encrypted with an ephemeral, symmetric, key
    encryption key.

    The check-summed Base58 format key decryption key is typed to
    Receiver Program manually. This prevents local key leak in following
    scenarios:

        1. CT is intercepted by an adversary on compromised Networked
           Computer, but no visual eavesdropping takes place.

        2. CT is not intercepted by an adversary on Networked Computer,
           but visual eavesdropping records key decryption key.

        3. CT is delivered from Source Computer to Destination Computer
           directly (bypassing compromised Networked Computer), and
           visual eavesdropping records key decryption key.

    Once the correct key decryption key is entered to Receiver Program,
    it will display the 2-hexadecimal confirmation code generated by
    the Transmitter Program. The code will be entered back to
    Transmitter Program to confirm the user has successfully delivered
    the key decryption key.

    The protocol is completed with Transmitter Program sending
    LOCAL_KEY_RDY signal to the Receiver Program, that then moves to
    wait for public keys from contact.
    """
    try:
        raise_if_traffic_masking(settings, only_if=local_key_db.has_keyset)

        print_message('Local key setup', bold=True, clear_before=True, padding_top=1, padding_bottom=1)

        kek = LocalKeyEncryptionKey()
        confirmation_code = ConfirmationCode.generate()

        encrypted_local_key_set = local_key_db.new_local_key(kek, confirmation_code)
        local_key_datagram      = DatagramReceiverLocalKey(encrypted_local_key_set)
        deliver_local_key(local_key_datagram, kek, confirmation_code, settings, queues)

        local_key_db.mark_local_key_as_delivered()
        local_key_db.export_local_keyset_to_sender_process(queues)

        # Notify Receiver Program that confirmation code was successfully entered
        queue_command(settings, queues, SerializedCommand(RxCommand.LOCAL_KEY_RDY))

        print_message('Successfully completed the local key exchange.', bold=True, clear_delay=1, padding_top=1)
        reset_terminal()

    except (EOFError, KeyboardInterrupt):
        raise SoftError('Local key setup aborted.', clear_after=True, clear_delay=1, padding_top=2)


def deliver_local_key(local_key_datagram : DatagramReceiverLocalKey,
                      kek                : 'LocalKeyEncryptionKey',
                      confirmation_code  : ConfirmationCode,
                      settings           : 'Settings',
                      queues             : 'TxQueue'
                      ) -> None:
    """Deliver encrypted local key to Destination Computer."""
    get_nc_bypass_confirmation(NCBypassState.NC_BYPASS_START, settings)

    queues.relay_packet.put( local_key_datagram )

    while True:
        print_key('Local key decryption key (to Receiver)', kek, settings)
        purp_code = get_confirmation_code(code_displayed_on='Receiver')

        if purp_code == confirmation_code:
            get_nc_bypass_confirmation(NCBypassState.NC_BYPASS_STOP, settings)
            break

        elif purp_code.is_resend_request:
            with phase('Resending local key', padding_top=2):
                queues.relay_packet.put( local_key_datagram )
            clear_previous_lines(no_lines=(9 if settings.local_testing_mode else 10))

        else:
            print_message(['Incorrect confirmation code. If Receiver did not receive',
                     'the encrypted local key, resend it by pressing <Enter>.'], padding_top=1)
            clear_previous_lines(no_lines=(9 if settings.local_testing_mode else 10), delay=2)
