name: TFC CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "deb https://deb.torproject.org/torproject.org focal main" | sudo tee -a /etc/apt/sources.list.d/torproject.list
          wget -O - -o /dev/null https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
          gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
          sudo apt update
          sudo apt install python3-setuptools python3-tk tor -y
          pip install pytest pytest-cov pyyaml coveralls
          pip install -r requirements-dev.txt
          export TZ=Europe/Helsinki
      - name: Unit Tests Common
        run: |
          py.test --cov=src tests/common
      - name: Unit Tests Receiver
        run: |
          py.test --cov=src tests/receiver
      - name: test_commands_g.py
        run: py.test --cov=src tests/receiver/test_commands_g.py
      - name: test_commands.py
        run: py.test --cov=src tests/receiver/test_commands.py
      - name: test_files.py
        run: py.test --cov=src tests/receiver/test_files.py
      - name: test_key_exchanges.py
        run: py.test --cov=src tests/receiver/test_key_exchanges.py
      - name: test_messages.py
        run: py.test --cov=src tests/receiver/test_messages.py
      - name: test_output_loop.py
        run: py.test --cov=src tests/receiver/test_output_loop.py
      - name: test_packet.py
        run: py.test --cov=src tests/receiver/test_packet.py
      - name: test_receiver_loop.py
        run: py.test --cov=src tests/receiver/test_receiver_loop.py
      - name: test_windows.py
        run: py.test --cov=src tests/receiver/test_windows.py


      - name: Unit Tests Relay
        run: |
          py.test --cov=src tests/relay
      - name: Unit Tests Transmitter
        run: |
          py.test --cov=src tests/transmitter
      - name: Unit Tests Other
        run: |
          py.test --cov=src tests/test_dd.py
